"""Generate frontend/dice.js: verified uniform-superposition circuits for D&D dice.

Build-time tooling — run by hand (`python backend/gen_dice.py`), NOT imported by
the FastAPI app (`backend.main`). It lives alongside the backend only because it
shares the same Qiskit dependency and the backend's gate whitelist.

For an N-faced die we want measurement outcomes 0..N-1 each with prob 1/N.
Powers of two are Hadamards; others use exact state preparation transpiled to
the backend gate whitelist. Output is a JS object the frontend drag-drops.
"""
import math
from pathlib import Path

import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit.circuit.library import StatePreparation
from qiskit.quantum_info import Statevector

# This script lives in backend/; frontend/ is its sibling under the repo root.
# Anchor the output path there so it works no matter where it's run from.
OUT_PATH = Path(__file__).resolve().parent.parent / "frontend" / "dice.js"

BASIS = ["h", "x", "y", "z", "s", "t", "sdg", "tdg",
         "rx", "ry", "rz", "cx", "cz", "swap", "cp", "ccx", "cswap"]
LABEL = {"h": "H", "x": "X", "y": "Y", "z": "Z", "s": "S", "t": "T",
         "sdg": "SDG", "tdg": "TDG", "rx": "RX", "ry": "RY", "rz": "RZ",
         "cx": "CX", "cz": "CZ", "swap": "SWAP", "cp": "CP",
         "ccx": "CCX", "cswap": "CSWAP"}
PARAM = {"rx", "ry", "rz", "cp"}

DICE = [2, 4, 6, 8, 10, 12, 20, 100]


def build(N):
    n = math.ceil(math.log2(N))
    if 2 ** n == N:
        qc = QuantumCircuit(n)
        for q in range(n):
            qc.h(q)
        return n, qc
    amps = np.zeros(2 ** n)
    amps[:N] = 1 / math.sqrt(N)
    qc = QuantumCircuit(n)
    qc.append(StatePreparation(amps), range(n))
    return n, transpile(qc, basis_gates=BASIS, optimization_level=3)


def js_gate(inst, qc):
    name = inst.operation.name
    qubits = [qc.find_bit(q).index for q in inst.qubits]
    param = round(float(inst.operation.params[0]), 10) if name in PARAM else "null"
    return f'{{label:"{LABEL[name]}",qubits:[{",".join(map(str, qubits))}],param:{param}}}'


def verify(N, qc):
    sv = Statevector.from_instruction(qc)
    probs = np.abs(sv.data) ** 2
    err = float(np.max(np.abs(probs[:N] - 1 / N)))
    leak = float(np.sum(probs[N:]))
    assert err < 1e-9 and leak < 1e-9, (N, err, leak)
    return err, leak


lines = [
    "// AUTO-GENERATED by gen_dice.py — verified uniform D&D dice circuits.",
    "// Each die prepares an equal superposition over faces 0..N-1 (measure to roll).",
    "// Loaded before app.js; gate objects match app.js's a() shape.",
    "const DICE_CIRCUITS = {",
]
for N in DICE:
    n, qc = build(N)
    err, leak = verify(N, qc)
    gates = ", ".join(js_gate(inst, qc) for inst in qc.data)
    desc = f"Fair d{N}: uniform over {N} outcomes (faces 0–{N - 1})."
    lines.append(f'  "d{N}": {{ n: {n}, desc: "{desc}", gates: [{gates}] }},')
    print(f"d{N}: n={n} gates={len(qc.data)} maxerr={err:.1e} leak={leak:.1e}")
lines.append("};")

OUT_PATH.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT_PATH}")
