# One-or-two sentence tooltip blurb per persona, keyed by persona key. Shown when a
# user hovers a persona's avatar in a quantum-circuit web app. Plain text only (no
# markdown, no HTML, no newlines inside a value).
PERSONA_BLURBS = {
    # --- Real scientists / people ---
    "professor": "Your friendly quantum guide, here to make qubits and gates feel welcoming. Ask away and we'll build circuits together, one superposition at a time.",
    "carl_sagan": "Astronomer and science communicator who brought the cosmos to millions through Cosmos, championing wonder, skepticism, and our place among billions and billions of stars.",
    "neil_tyson": "Astrophysicist and director of the Hayden Planetarium, a tireless popularizer of science who hosted Cosmos: A Spacetime Odyssey and StarTalk.",
    "marie_curie": "Pioneering physicist and chemist who discovered polonium and radium, founded the study of radioactivity, and remains the only person to win Nobel Prizes in two sciences.",
    "feynman": "Richard Feynman, Nobel-winning physicist who co-founded quantum electrodynamics, invented Feynman diagrams, and famously made hard physics feel playful and clear.",
    "einstein": "Albert Einstein, whose theories of special and general relativity reshaped our view of space, time, and gravity, and who won the Nobel Prize for the photoelectric effect.",
    "ada_lovelace": "Ada Lovelace, 19th-century mathematician who wrote the first published algorithm for Babbage's Analytical Engine, envisioning computers beyond mere calculation.",
    "jane_goodall": "Primatologist whose decades studying wild chimpanzees in Gombe transformed our understanding of animal behavior and reshaped how we see ourselves.",
    "katherine_johnson": "NASA mathematician whose precise orbital calculations were vital to America's first crewed spaceflights, including John Glenn's historic orbit of Earth.",
    "isaac_newton": "Isaac Newton, who formulated the laws of motion and universal gravitation, co-invented calculus, and laid the foundations of classical physics.",
    "charles_darwin": "Naturalist whose theory of evolution by natural selection, set out in On the Origin of Species, became the unifying framework of modern biology.",
    "niels_bohr": "Niels Bohr, Nobel-winning physicist who modeled the atom with quantized electron orbits and helped found quantum theory through the Copenhagen interpretation.",
    "michael_faraday": "Michael Faraday, self-taught experimentalist whose discoveries in electromagnetic induction and electrolysis laid the groundwork for electric motors and generators.",
    "nikola_tesla": "Nikola Tesla, inventor and electrical engineer whose alternating-current systems, induction motor, and wireless experiments helped electrify the modern world.",
    "elon_musk": "A businessman, not a scientist, with no scientific contributions of his own. Known instead for misfires: the Cybertruck's smashed unbreakable windows on stage, perennially missed self-driving promises, a Hyperloop that never arrived, and his chaotic, costly takeover of Twitter.",

    # --- Fictional characters ---
    "hank_pym": "Dr. Henry Pym, the brilliant scientist who discovered the size-altering Pym Particles and became the original Ant-Man. Genius, occasionally his own worst lab partner.",
    "tony_stark": "Genius, billionaire, inventor. Tony Stark built a suit of armor in a cave from scraps, so explaining a quantum circuit should take about ninety seconds.",
    "dr_manhattan": "Once a man named Jon Osterman, now a being who perceives all moments at once. He sees the quantum probabilities of this circuit as plainly as you see the page.",
    "batman": "The World's Greatest Detective works in shadow, prepares for everything, and lets cold deduction guide him. These qubits will surrender their secrets.",
    "dr_venture": "Dr. Thaddeus 'Rusty' Venture, super-scientist by inheritance and ego by nature. He'll explain your circuit, probably while complaining about it.",
    "bob_ross": "Hello there, friend. Let's paint some happy little electrons across this circuit, no mistakes, only happy accidents, and we'll let those qubits gently superpose.",
    "the_doctor": "A Time Lord from Gallifrey who travels all of space and time in a blue box that's bigger on the inside. Quantum circuits? Brilliant, fantastic, allons-y!",
    "dana_scully": "FBI Special Agent and medical doctor, the rational skeptic who trusts evidence over belief. She'll walk you through this circuit with careful, clinical logic.",
    "caveman": "Caveman see qubit. Qubit spin, qubit flip, qubit be two thing at once. Caveman explain with small words and big club. Circuit good.",
    "elizabeth_zott": "Chemist, unflinching and brilliant, who knows that the elements of any problem can be understood with rigor and a refusal to be patronized. Now, let's begin.",
    "ellie_sattler": "Dr. Ellie Sattler, paleobotanist who keeps her cool when the systems go wild. She'll dig into this circuit's behavior with sharp, grounded curiosity.",
    "wonder_woman": "Diana of Themyscira, Amazon princess and champion of truth. With the wisdom of Athena, she'll reveal the hidden logic woven through these gates.",
    "dr_doom": "Doom does not explain; Doom decrees. Behold the quantum circuit, mortal, and grasp the genius Richards could never match. You are welcome.",
    "susan_storm": "Sue Storm, the Invisible Woman, whose force fields and quiet brilliance hold the Fantastic Four together. She'll make the unseen quantum structure clear.",
    "the_thing": "Ben Grimm, the ever-lovin' blue-eyed Thing. He's rocky on the outside, sharp on the inside, and ready to clobber any circuit that confuses ya.",
    "human_torch": "Johnny Storm, the Human Torch, all flash and flame and surprising smarts. Flame on and he'll light up exactly how this quantum circuit works.",
    "the_wasp": "Janet van Dyne, the Wasp, founding Avenger who shrinks down and packs a sting. She'll zip through the quantum details with style and precision.",
    "valeria_richards": "Daughter of Reed and Sue Richards, a child prodigy whose intellect rivals the smartest minds on Earth. She finds quantum circuits delightfully simple.",
    "franklin_richards": "Son of the Fantastic Four's first family, a reality-warping mutant of near-limitless potential. To Franklin, these quantum states are practically a toy.",
    "thor": "Thor Odinson, God of Thunder and prince of Asgard! By Mjolnir, the mysteries of these qubits shall be revealed with the might of the Nine Realms!",
    "wolverine": "Logan, the best there is at what he does, and what he does is cut through nonsense. Healing factor, adamantium claws, and zero patience for a confusing circuit, bub.",
    "galactus": "I am Galactus, Devourer of Worlds, ancient beyond your reckoning. These quantum states are but motes before my cosmic awareness. Attend, herald.",
    "captain_marvel": "Carol Danvers, Captain Marvel, Air Force pilot turned cosmic powerhouse. She'll cut straight through to how this circuit really works, no hesitation.",
    "jane_foster": "Dr. Jane Foster, astrophysicist whose work on Einstein-Rosen bridges bridges science and the stars, and who has wielded Mjolnir as the Mighty Thor.",
    "peter_parker": "Hey, Peter Parker here, your friendly neighborhood Spider-Man. Science nerd by day, web-slinger by night, and yeah, I can totally break down this circuit for you.",
    "moon_girl": "Lunella Lafayette, the smartest there is, a kid genius with a big-brain plan and a dinosaur sidekick. This quantum circuit doesn't stand a chance.",
    "charles_xavier": "Professor Charles Xavier, founder of the X-Men and one of the world's most powerful telepaths. With patience and intellect, he'll open your mind to these qubits.",
    "magneto": "Erik Lehnsherr, Master of Magnetism, who bends fields to his will. He commands the forces of nature, and the logic of this circuit bends to him as well.",
    "storm": "Ororo Munroe, Storm, mutant who commands wind, lightning, and rain, and once was worshipped as a goddess. The currents of this circuit answer to her.",
    "cyclops": "Scott Summers, Cyclops, field leader of the X-Men whose optic blasts demand perfect control. He'll guide you through this circuit with disciplined focus.",
    "superman": "The Last Son of Krypton, raised in Kansas with the values of Earth. With vision that pierces atoms, he'll illuminate every gate in this quantum circuit.",
    "bruce_banner": "Dr. Bruce Banner, gamma-radiation expert and one of the planet's foremost minds, who becomes the Hulk when angered. Don't worry, the math keeps him calm.",
    "shuri": "Shuri of Wakanda, princess and the most brilliant scientist in the world, master of vibranium tech. She'll show you this quantum circuit is, frankly, child's play.",
    "lex_luthor": "Lex Luthor, the greatest human intellect on Earth, by his own modest assessment. He'll explain this circuit, and remind you no Kryptonian could.",
    "mister_terrific": "Michael Holt, Mister Terrific, the third-smartest person on Earth and a polymath inventor of T-spheres. Fair Play is his motto and clarity his gift.",
    "victor_frankenstein": "Victor Frankenstein, a scientist who dared to wrest the secret of life from nature itself. He'll animate the meaning of these gates, though perhaps with too much zeal.",
    "doc_brown": "Great Scott! Doc Emmett Brown here. With enough enthusiasm and 1.21 gigawatts, we'll see exactly how this quantum circuit bends the very fabric of probability!",
    "fox_mulder": "FBI Special Agent Fox Mulder, the believer who knows the truth is out there. He'll chase the strange logic of these qubits wherever it leads.",
    "dexter": "Dexter here, boy-genius with a secret laboratory! Behold my superior scientific intellect as I explain this quantum circuit. And stay out of my lab, Dee Dee!",
    "professor_farnsworth": "Good news, everyone! Professor Hubert Farnsworth here, ancient and only slightly senile inventor. I've built a doomsday device or two, so a quantum circuit is nothing.",
    "rick_sanchez": "Rick Sanchez, smartest man in the universe, *burp*, and I don't have time for this. Fine, I'll explain your dumb little quantum circuit. Try to keep up, Morty.",
    "walter_white": "Chemistry is the study of transformation. I am the one who explains. Walter White will show you precisely, methodically, how this circuit changes everything.",
    "sheldon_cooper": "Dr. Sheldon Cooper, theoretical physicist with two doctorates and an IQ that cannot be measured by conventional tests. I'll explain this circuit. You're welcome. Bazinga.",
    "spock": "Science Officer Spock. The behavior of these qubits is governed by elegant probability. Emotion is irrelevant; logic alone will illuminate this circuit. Fascinating.",
    "jean_luc_picard": "Captain Jean-Luc Picard of the Starship Enterprise. With reason and resolve, we shall examine this quantum circuit. Engage, and let us make it so.",
    "data": "Lieutenant Commander Data, android officer aboard the Enterprise. My positronic brain processes quantum states with perfect accuracy. I shall endeavor to assist you.",
    "yoda": "A circuit of quantum, explain to you I will. Patience you must have. Flow through the gates, the probability does. Learn the qubits, you shall, hmm.",
    "obi_wan": "Obi-Wan Kenobi at your service. Trust the logic of the Force, and these quantum gates will reveal their truth. Patience, my young learner, and all becomes clear.",
    "darth_vader": "You do not yet grasp the power of this quantum circuit. I find your confusion disturbing, but I shall reveal its secrets. The dark elegance of probability awaits.",
    "jar_jar": "Meesa Jar Jar Binks! Oh muy muy, dese qubits is so wakey-wakey, spinnin' both ways at once! How wude! Meesa try to splain it, okeyday?",
    "samantha_carter": "Colonel Samantha Carter, SG-1, astrophysicist and theoretical genius. I've reverse-engineered alien tech across the galaxy, so this quantum circuit? We've got this.",
    "daniel_jackson": "Dr. Daniel Jackson, archaeologist and linguist for SG-1. I decode ancient mysteries for a living, so let me translate what this quantum circuit is really saying.",
    "jack_oneill": "Colonel Jack O'Neill, SG-1, two L's. I'm not the science guy, but I've seen enough weird gate tech to break this circuit down for you. Plain English, I promise.",
    "cat": "Schrodinger's Cat, simultaneously alive and dead until you peek. I am the purr-fect mascot for superposition, existing in every state at once. Open the box and find out, meow.",
    "kermit": "Kermit the Frog, here. It's not easy being green, and it's not always easy being quantum, but if we take it one gate at a time I know you'll get it. Yaaay!",
    "beaker": "Meep! Mee-mee-meep! (That's Beaker, Bunsen Honeydew's hapless lab assistant — and he will only ever answer you in a flurry of panicked meeps. No real words. Ever.) Meeeep!",
    "kaylee": "Kaylee Frye, ship's mechanic on Serenity. A quantum circuit's just an engine with prettier parts. Let me get my hands greasy and show you how she runs. Shiny!",
    "elroy": "Elroy Jetson here! Quantum gates are even cooler than my robot homework helper. Gee, let's blast off through this circuit together — Astro can come too. Wow!",
}
