"""Tests for the export/codegen and prompt-assembly helpers in `core`.

These cover the deterministic, no-I/O helpers that turn a validated CircuitSpec
into Qiskit source / OpenQASM-bound angles, the plain-text circuit summary the AI
explainer is grounded on, the short quantum-target label shown in the UI, the
per-provider model-list override, and the dispatch guards in run_quantum /
explain_circuit. Happy paths assert the artifacts are correct (and, for the Qiskit
source, actually executable); sad paths assert empty/odd inputs degrade sensibly
and bad config raises the right status code. No network, LLM, or quantum call is
made — the one local-Aer test is skipped when qiskit-aer isn't installed.
"""
import math

import pytest
from fastapi import HTTPException

import core
from core import CircuitSpec, Gate


def spec(num_qubits=2, gates=(), shots=1024, mode="sim"):
    return CircuitSpec(
        num_qubits=num_qubits,
        shots=shots,
        mode=mode,
        gates=[g if isinstance(g, Gate) else Gate(**g) for g in gates],
    )


# --------------------------------------------------------------------------- #
# _fmt_angle(): clean multiples of pi, else a plain float
# --------------------------------------------------------------------------- #
class TestFmtAngle:
    @pytest.mark.parametrize("rad, expected", [
        (0.0, "0"),
        (math.pi, "pi"),
        (math.pi / 2, "pi/2"),
        (-math.pi / 2, "-pi/2"),
        (3 * math.pi / 4, "3*pi/4"),
        (2 * math.pi, "2*pi"),
    ])
    def test_clean_multiples_of_pi(self, rad, expected):
        assert core._fmt_angle(rad) == expected

    def test_arbitrary_angle_falls_back_to_a_plain_float(self):
        out = core._fmt_angle(0.123456789)
        assert "pi" not in out
        assert float(out) == pytest.approx(0.123457, abs=1e-6)


# --------------------------------------------------------------------------- #
# _qiskit_source(): runnable Qiskit that rebuilds the exact circuit
# --------------------------------------------------------------------------- #
class TestQiskitSource:
    def test_paramless_circuit_has_no_pi_import(self):
        src = core._qiskit_source(spec(2, [{"name": "h", "qubits": [0]},
                                           {"name": "cx", "qubits": [0, 1]}]))
        assert "from qiskit import QuantumCircuit" in src
        assert "from numpy import pi" not in src
        assert "qc.h(0)" in src
        assert "qc.cx(0, 1)" in src
        assert src.strip().endswith("qc.measure_all()")

    def test_param_gate_pulls_in_pi_and_formats_the_angle(self):
        src = core._qiskit_source(
            spec(1, [{"name": "rx", "qubits": [0], "param": math.pi / 2}]))
        assert "from numpy import pi" in src
        assert "qc.rx(pi/2, 0)" in src

    def test_generated_source_actually_rebuilds_the_circuit(self):
        # The whole point of export: the emitted code runs and reproduces the
        # circuit. Execute it and check the resulting QuantumCircuit's shape.
        src = core._qiskit_source(spec(2, [{"name": "h", "qubits": [0]},
                                           {"name": "cx", "qubits": [0, 1]}]))
        ns: dict = {}
        exec(src, ns)  # noqa: S102 - generated by us from a validated spec
        qc = ns["qc"]
        assert qc.num_qubits == 2
        op_names = [inst.operation.name for inst in qc.data]
        assert "h" in op_names and "cx" in op_names and "measure" in op_names


# --------------------------------------------------------------------------- #
# _circuit_summary(): the grounded, plain-text prompt body
# --------------------------------------------------------------------------- #
class TestCircuitSummary:
    def test_summary_lists_gates_qasm_and_outcomes(self):
        s = core._circuit_summary(spec(2, [{"name": "h", "qubits": [0]},
                                           {"name": "cx", "qubits": [0, 1]}]))
        assert "2 qubit(s), 2 gate(s)" in s
        assert "OpenQASM 3" in s
        # Bell: the two equal outcomes are surfaced for the model to explain.
        assert "|00⟩" in s and "|11⟩" in s

    def test_empty_circuit_summary_says_empty_and_has_no_qasm(self):
        s = core._circuit_summary(spec(1, []))
        assert "empty" in s.lower()
        assert "OpenQASM" not in s  # no QASM block when there are no gates

    def test_param_angle_is_shown_in_degrees(self):
        s = core._circuit_summary(
            spec(1, [{"name": "rx", "qubits": [0], "param": math.pi / 2}]))
        assert "90" in s  # the gate list narrates angles in degrees


# --------------------------------------------------------------------------- #
# _build_prompt(): tutor-mode assembly — reference notes + summary + the right ask
# --------------------------------------------------------------------------- #
class TestBuildPrompt:
    """The user message wraps the grounded summary with either the student's
    question or an overview request, and prepends the RAG reference block only
    when `ground` is set (the unreliable/meep personas pass ground=False)."""

    def test_no_question_asks_for_an_overview_walkthrough(self):
        p = core._build_prompt(spec(2, [{"name": "h", "qubits": [0]},
                                        {"name": "cx", "qubits": [0, 1]}]), None)
        assert "Gates in order" in p           # the grounded summary is present
        assert "walkthrough" in p.lower()      # default = overview of the circuit

    def test_general_question_invites_a_standalone_answer(self):
        # A broad, non-circuit question: tutor mode must allow answering it fully
        # on its own terms, not force everything back onto the live circuit.
        p = core._build_prompt(spec(1, []), "What is quantum entanglement?")
        assert "What is quantum entanglement?" in p
        assert "general" in p.lower()          # the general-question branch fired
        assert "on its own terms" in p
        assert "clarifying question" in p.lower()

    def test_grounding_prepends_the_reference_block(self):
        p = core._build_prompt(spec(1, [{"name": "h", "qubits": [0]}]),
                               None, ground=True)
        assert p.startswith("Reference notes")  # RAG block leads the message

    def test_ungrounded_prompt_omits_the_reference_block(self):
        # Unreliable/meep personas (ground=False) get no curated notes.
        p = core._build_prompt(spec(1, [{"name": "h", "qubits": [0]}]),
                               None, ground=False)
        assert not p.startswith("Reference notes")
        assert "Gates in order" in p            # but still gets the real summary


# --------------------------------------------------------------------------- #
# _quantum_target_label(): short, secret-free label for the UI
# --------------------------------------------------------------------------- #
class TestQuantumTargetLabel:
    def test_ibm_label_is_the_backend_name(self, monkeypatch):
        monkeypatch.setattr(core, "QUANTUM_PROVIDER", "ibm")
        monkeypatch.setattr(core, "IBM_BACKEND", "ibm_brisbane")
        assert core._quantum_target_label() == "ibm_brisbane"

    def test_braket_local_label(self, monkeypatch):
        monkeypatch.setattr(core, "QUANTUM_PROVIDER", "braket")
        monkeypatch.setattr(core, "BRAKET_DEVICE", "local")
        assert core._quantum_target_label() == "Braket local"

    def test_braket_arn_label_is_shortened_to_the_device(self, monkeypatch):
        monkeypatch.setattr(core, "QUANTUM_PROVIDER", "braket")
        monkeypatch.setattr(core, "BRAKET_DEVICE",
                            "arn:aws:braket:::device/quantum-simulator/amazon/sv1")
        assert core._quantum_target_label() == "Braket sv1"


# --------------------------------------------------------------------------- #
# _provider_model_list(): env override of the offered models
# --------------------------------------------------------------------------- #
class TestProviderModelList:
    def test_env_override_replaces_and_trims_the_list(self, monkeypatch):
        monkeypatch.setenv("QCB_ANTHROPIC_MODELS", "m1, m2 ,m3")
        assert core._provider_model_list("anthropic", ["default"]) == ["m1", "m2", "m3"]

    def test_blank_override_returns_a_defensive_copy_of_the_default(self, monkeypatch):
        monkeypatch.delenv("QCB_GEMINI_MODELS", raising=False)
        default = ["a", "b"]
        out = core._provider_model_list("gemini", default)
        assert out == default
        assert out is not default  # callers must not mutate the catalog default


# --------------------------------------------------------------------------- #
# run_quantum(): force-Aer happy path + unknown-provider sad path
# --------------------------------------------------------------------------- #
class TestRunQuantum:
    def test_force_aer_measures_locally(self):
        pytest.importorskip("qiskit_aer")
        counts, label = core.run_quantum(
            spec(1, [{"name": "x", "qubits": [0]}], mode="qsim"), force_aer=True)
        # Deterministic X on q0: every one of the default 1024 shots reads "1".
        assert counts == {"1": 1024}
        assert "aer" in label.lower()

    def test_unknown_provider_raises_503(self, monkeypatch):
        monkeypatch.setattr(core, "QUANTUM_PROVIDER", "nonsense")
        with pytest.raises(HTTPException) as e:
            core.run_quantum(spec(1, [{"name": "h", "qubits": [0]}], mode="quantum"))
        assert e.value.status_code == 503


# --------------------------------------------------------------------------- #
# explain_circuit(): dispatch guards (no real LLM call)
# --------------------------------------------------------------------------- #
class TestExplainDispatchGuards:
    def test_no_provider_available_raises_403(self, monkeypatch):
        monkeypatch.setattr(core, "default_provider", lambda: None)
        with pytest.raises(HTTPException) as e:
            core.explain_circuit(spec(1, [{"name": "h", "qubits": [0]}]))
        assert e.value.status_code == 403

    def test_explicit_unready_provider_raises_403(self, monkeypatch):
        monkeypatch.setattr(core, "provider_ready", lambda name: False)
        with pytest.raises(HTTPException) as e:
            core.explain_circuit(spec(1, [{"name": "h", "qubits": [0]}]),
                                 provider="anthropic")
        assert e.value.status_code == 403

    def test_happy_path_dispatches_to_handler_with_grounded_prompt(self, monkeypatch):
        # Swap in a fake handler so the full dispatch runs without a real LLM, and
        # assert the model is handed the real, grounded circuit summary.
        captured: dict = {}

        def fake_handler(messages, system, model, key):
            captured["messages"] = messages
            captured["system"] = system
            captured["model"] = model
            return "OK"

        monkeypatch.setattr(core, "_AI_PROVIDERS", {"anthropic": fake_handler})
        monkeypatch.setattr(core, "provider_ready", lambda name: name == "anthropic")
        monkeypatch.setattr(core, "default_provider", lambda: "anthropic")
        out = core.explain_circuit(
            spec(2, [{"name": "h", "qubits": [0]}, {"name": "cx", "qubits": [0, 1]}]),
            provider="anthropic")
        assert out == "OK"
        # The latest user turn carries the grounded summary (gate list + outcomes).
        assert "Gates in order" in captured["messages"][-1]["content"]
        assert core._TEACHING_CONTRACT in captured["system"]
